- name: Check Distro compatibility
  fail:
    msg: "ERPNext requires Ubuntu 20.04 LTS or newer."
  when: 
    - erpnext_version in ['14', '15']
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version is version('20.04', '<')

- name: Validate additional ERPNext 15 requirements
  fail:
    msg: "ERPNext 15 requires Ubuntu 22.04 or newer."
  when: 
    - erpnext_version == '15'
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version is version('22.04', '<')

- name: Check Debian compatibility
  fail:
    msg: "ERPNext is not compatible with your Debian version."
  when: 
    - ansible_distribution == 'Debian'
    - ansible_distribution_version is version('9', '<')

- name: Check for unsupported distributions
  fail:
    msg: "This script is only compatible with Ubuntu or Debian."
  when: ansible_distribution not in ['Ubuntu', 'Debian']
