- name: Setup Supervisor and Nginx configuration for production
  command: bench setup production {{ non_root_user }}
  args:
    chdir: "{{ non_root_home }}/frappe-bench"

- name: Apply necessary permissions to Supervisor
  lineinfile:
    path: /etc/supervisor/supervisord.conf
    line: 'chown={{ ansible_user_id }}:{{ ansible_user_id }}'
    insertafter: '^\\[unix_http_server\\]'

- name: Restart Supervisor service
  service:
    name: supervisor
    state: restarted

- name: Enable and resume the scheduler for the site
  command: bench --site {{ site_name }} scheduler {{ item }}
  loop:
    - enable
    - resume
  args:
    chdir: "{{ non_root_home }}/frappe-bench"

- name: Optimize environment permissions
  file:
    path: "{{ non_root_home}}"
    mode: '0755'
    recurse: yes

- name: Final setup of Supervisor and Nginx configuration for production
  shell: yes | bench setup production {{ non_root_user }}
  args:
    chdir: "{{ non_root_home }}/frappe-bench"
  become: yes
