- name: Install NVM (Node Version Manager)
  become: yes
  become_user: "{{ non_root_user }}"
  shell: |
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
  args:
    creates: "{{ non_root_home }}/.nvm/nvm.sh"


- name: Add NVM environment variables to non-root user's .profile
  become: yes
  become_user: "{{ non_root_user }}"
  lineinfile:
    path: "{{ non_root_home }}/.profile"
    line: "{{ item }}"
    create: yes
  loop:
    - 'export NVM_DIR="{{ non_root_home }}/.nvm"'
    - '[ -s "{{ non_root_home }}/.nvm/nvm.sh" ] && \. "{{ non_root_home }}/.nvm/nvm.sh"'
    - '[ -s "{{ non_root_home }}/.nvm/bash_completion" ] && \. "{{ non_root_home }}/.nvm/bash_completion"'

- name: Install Node.js version based on ERPNext requirements
  become: yes
  become_user: "{{ non_root_user }}"
  shell: |
    . "{{ non_root_home }}/.nvm/nvm.sh"
    nvm install {{ node_version }}
  args:
    executable: /bin/bash
  environment:
    NVM_DIR: "{{ non_root_home }}/.nvm"
  async: 600
  poll: 15



- name: Install npm
  apt:
    name: npm
    state: present
  become: yes

- name: Install yarn
  npm:
    name: yarn
    global: yes
  become: yes

- name: Check if Python 3.10 is installed
  command: python3.10 --version
  register: python_version_output
  ignore_errors: true
  changed_when: false

- name: Set python_version fact
  set_fact:
    python_version: "{{ python_version_output.stdout | regex_search('Python\\s(3\\.10\\.\\d+)', '\\1') | first }}"
  when: python_version_output.stdout is defined

- name: Set up Python virtual environment
  shell: "python3.10 -m venv {{ non_root_user }} && source {{ non_root_user }}/bin/activate"
  args:
    creates: "{{ non_root_home }}/{{ non_root_user }}/bin/activate"
  when: python_version is defined and python_version is version('3.10', '<')
  environment:
    NVM_DIR: "{{ non_root_home }}/.nvm"
