- name: Install basic Python packages and Redis Server
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - python3-dev
    - python3-setuptools
    - python3-venv
    - python3-pip
    - python3-distutils
    - redis-server

- name: Determine system architecture
  command: dpkg --print-architecture
  register: architecture

- name: Set wkhtmltopdf download URL based on architecture
  set_fact:
    wkhtmltopdf_url: "https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.jammy_{{ architecture.stdout }}.deb"
    wkhtmltopdf_deb: "/tmp/wkhtmltox_0.12.6.1-2.jammy_{{ architecture.stdout }}.deb"

- name: Download wkhtmltopdf
  get_url:
    url: "{{ wkhtmltopdf_url }}"
    dest: "{{ wkhtmltopdf_deb }}"

- name: Install wkhtmltopdf
  apt:
    deb: "{{ wkhtmltopdf_deb }}"


- name: Install additional font and rendering packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - fontconfig
    - xvfb
    - libfontconfig
    - xfonts-base
    - xfonts-75dpi
    - libxrender1

- name: Clean up downloaded wkhtmltopdf package
  file:
    path: "/tmp/wkhtmltox_0.12.6.1-2.jammy_amd64.deb"
    state: absent
