- name: Install frappe-bench
  pip:
    name: frappe-bench
    executable: pip3
  become: no

- name: Initialize frappe-bench with ERPNext
  command: >
    bench init frappe-bench --version version-{{ erpnext_version }}
    --verbose --install-app erpnext --version version-{{ erpnext_version }}
  args:
    chdir: "{{ non_root_home }}"
    creates: "{{ non_root_home }}/frappe-bench"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ non_root_home }}/.local/bin"
  become: no
