- name: Ensure .nvm directory is owned by non-root user
  file:
    path: "{{ non_root_home }}/.nvm"
    owner: "{{ non_root_user }}"
    group: "{{ non_root_user }}"
    recurse: yes
  become: yes

- name: Check if frappe-bench directory exists
  stat:
    path: "{{ non_root_home }}/frappe-bench"
  register: frappe_bench_stat

- name: Remove frappe-bench directory if it exists
  file:
    path: "{{ non_root_home }}/frappe-bench"
    state: absent
  when: frappe_bench_stat.stat.exists
  become: yes

- name: Install frappe-bench
  pip:
    name: frappe-bench
    executable: pip3
  become: yes

- name: Initialize frappe-bench with ERPNext
  become: yes
  become_user: "{{ non_root_user }}"
  shell: |
    . "{{ non_root_home }}/.nvm/nvm.sh" &&
    bench init frappe-bench --version version-{{ erpnext_version }} --verbose --install-app erpnext --version version-{{ erpnext_version }}
  args:
    chdir: "{{ non_root_home }}"
    creates: "{{ non_root_home }}/frappe-bench"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ non_root_home }}/.local/bin"
    NVM_DIR: "{{ non_root_home }}/.nvm"

