- name: Install frappe-bench
  pip:
    name: frappe-bench
    executable: pip3
  become: no

- name: Initialize frappe-bench with ERPNext
  become: yes
  become_user: "{{ non_root_user }}"
  command: >
    . "{{ non_root_home }}/.nvm/nvm.sh" &&
    bench init frappe-bench --version version-{{ erpnext_version }}
    --verbose --install-app erpnext --version version-{{ erpnext_version }}
  args:
    chdir: "{{ non_root_home }}"
    creates: "{{ non_root_home }}/frappe-bench"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ non_root_home }}/.local/bin"
    NVM_DIR: "{{ non_root_home }}/.nvm"
